---
title: "课后练习"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

***

**说明：** 

+ 练习以R语言实现；
+ 软件下载地址请参考[课程资源](https://zhu-group.github.io/ams/resource.html)
+ 部分教程请参考南科大环境学院《环境数据分析》网站。网站为英文，请自行翻译；
+ 灰色框内为代码，白色框内及图片为输出结果。

***

# RStudio桌面版基础操作

请参考[RStudio桌面版基础操作](https://zhu-group.github.io/ese335/S01.html#First_look_at_RStudio)

# R语言基础教程

请参考[R语言基础教程](https://zhu-group.github.io/ese335/S01.html#Quick_R_tutorial)

# 1 随机采样

```{r}
# 创建数据
data <- c(1, 2, 6, 4, 5, 6, 7, 8, 3, 6, 9)

# 函数库
library(base)

# sample函数
# 由以上数据中，随机采3个数据
sample(data, 3)

# 其他采样方式可用查看sample函数
```

# 2 基础统计量

```{r}
# 函数库
library(base)

# 基础统计量，分布为：
# 最小值 第一分位数 中位数 均值 第三分位数 最大值 
summary(data)

# 标准差
sd(data)

# 半内四分范围
IQR(data)

# 百分位数
# probs=0.25 表示25%分位数
quantile(data, probs=0.25)
```

# 3 偏度与峰态系数

```{r}
# 函数库
library(moments)

# 偏度系数
skewness(data)

# 峰态系数
kurtosis(data)
```

# 4 频率分布图

```{r}
# 函数库
library(base)

# 频率分布图
hist(data)

# 其他绘制方式可用查看hist函数
```

# 5 Box-Whisker图

```{r}
# 函数库
library(base)

# Box-Whisker分布图
boxplot(data)

# 其他绘制方式可用查看boxplot函数
```

# 6 正态分布概率密度

```{r}
# 函数库
library(base)

# 创建数列，-5到5，步长0.01 
x        <- seq(-5.0, 5.0, by=0.01)

# 输出正态分布概率密度
# Mean = 0, sd = 1
density1 <- dnorm(x, 0, 1)

# 画图
plot(x, density1, col="black", xlab="", ylab="Density", 
     type="l", lwd=3, cex=2, 
     xlim=c(-5.0, 5.0),
     main="PDF of normal distributions")

# 输出正态分布概率密度
# Mean = 1, sd = 1
density2  <- dnorm(x, 1, 1)
lines(x, density2, col="blue", xlab="", ylab="Density", 
     type="l", lwd=3, cex=2)

# 输出正态分布概率密度
# Mean = 0, sd = 3
density3  <- dnorm(x, 0, 3)
lines(x, density3, col="red", xlab="", ylab="Density", 
     type="l", lwd=3, cex=2)

# 添加图例
text(-4, 0.35, "N(0, 1)", col="black",   cex=2)
text(-4, 0.30, "N(1, 1)", col="blue",  cex=2)
text(-4, 0.25, "N(0, 9)", col="red", cex=2)
```

其他请参考[正态分布](https://zhu-group.github.io/ese335/S05.html#Normal_distribution)

# 7 Box-Cox变换

请参考[Box-Cox变换](https://zhu-group.github.io/ese335/S05.html#Normal_transformation)

# 8 异常值检验

请参考[异常值检验](https://zhu-group.github.io/ese335/S09.html#Outliers)

# 9 数据独立性检验

```{r}
# 函数库
library(randtests)

# 中位数游程检验
# p-value大于0.05，无法拒绝H0，即数据独立
runs.test(data)
```

其他请参考[独立性检验](https://zhu-group.github.io/ese335/S09.html#Independence)

# 10 *t* 检验

```{r}
# 函数库
library(base)

# 创建样本
Sample1   <- c(78, 83, 68, 72, 88, 75, 89, 76, 83, 90, 72, 79)
Sample2   <- c(73, 88, 74, 77, 91, 79, 93, 81, 82, 89, 77, 85)

# 根据实际情况，注意选择不同t检验

# 单样本t检验
# 检验：总体均值是否显著大于70
# p-value小于0.05，拒绝H0，即总体均值显著大于70
t.test(Sample1, mu=70, alternative ="greater")

# 独立样本t检验，假设总体方差相等
# 检验：总体均值是否相等
# p-value小于0.05，拒绝H0，即总体均值显著不等
t.test(Sample1, Sample2, alternative="two.sided", var.equal=T)

# 独立样本t检验，假设总体方差不等
# 检验：总体均值是否相等
# p-value小于0.05，拒绝H0，即总体均值显著不等
t.test(Sample1, Sample2, alternative="two.sided", var.equal=F)

# 配对样本t检验
# 检验：配对总体均值是否相等
# p-value小于0.05，拒绝H0，即配对总体均值显著不等
t.test(Sample1, Sample2, alternative="two.sided", paired=T)
```

# 11 正态性检验
```{r}
# 函数库
library(base)

# Shapiro-Wilk测试
# 检验：样本来自正态总体
# p-value大于0.05，无法拒绝H0，即样本来自正态总体
shapiro.test(Sample1)

# 函数库
library(nortest) 
# Lilliefors（Kolmogorov-Smirnov）测试
# 检验：样本来自正态总体
# p-value大于0.05，无法拒绝H0，即样本来自正态总体
lillie.test(Sample2)
```

# 12 方差分析及补充分析

请参考[方差分析](https://zhu-group.github.io/ese335/S10.html#One-way_ANOVA_with_R)与[补充分析](https://zhu-group.github.io/ese335/S11.html#Post-hoc_test_after_one-way_ANOVA)

# 13 相关分析

```{r}

# 创建数据
x <- rnorm(20,0,1)
y <- 2*x+rnorm(20,0,0.5)

# 散点图
plot(x,y)

# 根据实际情况，注意选择不同相关性检验

# 函数库
library(base)

# Pearson相关性检验
# 检验：两总体是否相关
# p-value小于0.05，拒绝H0，即两总体显著相关
cor.test(x, y, method="pearson", alternative="two.sided", conf.level=0.95)

# Spearman相关性检验
# 检验：两总体是否相关
# p-value小于0.05，拒绝H0，即两总体显著相关
cor.test(x, y, method="spearman", alternative="two.sided", conf.level=0.95)

# Kendall相关性检验
# 检验：两总体是否相关
# p-value小于0.05，拒绝H0，即两总体显著相关
cor.test(x, y, method="kendall", alternative="two.sided", conf.level=0.95)
```

# 14 非参数方法

请参考[非参数方法总结](https://zhu-group.github.io/ese335/S13.html#Summary_of_non-parametric_tests)

# 15 单变量简单线性回归

```{r}
# 创建数据
x <- rnorm(20,0,1)
y <- 2*x+rnorm(20,0,0.5)

# 散点图
plot(x,y)

# 基于最小二乘法，获取最优拟合线的斜率与截距
reg            <- lm( y ~ x )

# 输出回归结果
# Estimate下分别对应截距与斜率
# Pr对于截距与斜率的p-value，小于0.05, 说明总体参数显著不为0
# Multiple R-squared为决定系数（R2）
summary(reg)

# 添加回归线
abline(reg$coefficients[1], reg$coefficients[2], 
       col="red", lty=2, lwd=2)
```